// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA30JCgNeQ98Y0jZQhQ4og3qjsXiRDWGiA',
    appId: '1:186645707534:web:e99034dedbe4cfcb1f755f',
    messagingSenderId: '186645707534',
    projectId: 'elmasa-502219',
    authDomain: 'elmasa-502219.firebaseapp.com',
    storageBucket: 'elmasa-502219.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTWdtg1ms3i6jmBKDCRVp0dDjIpxHgoA0',
    appId: '1:186645707534:android:bfa674dec3e6cc111f755f',
    messagingSenderId: '186645707534',
    projectId: 'elmasa-502219',
    storageBucket: 'elmasa-502219.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIkZuKRdhvwXg3ufkca1H_LsSG1dFeyY',
    appId: '1:186645707534:ios:cf36f5b46e0cbbab1f755f',
    messagingSenderId: '186645707534',
    projectId: 'elmasa-502219',
    storageBucket: 'elmasa-502219.firebasestorage.app',
    iosClientId: '186645707534-eqsldonr1m4mis7fv8u87vh47vbhie29.apps.googleusercontent.com',
    iosBundleId: 'com.amir.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaIkZuKRdhvwXg3ufkca1H_LsSG1dFeyY',
    appId: '1:186645707534:ios:cf36f5b46e0cbbab1f755f',
    messagingSenderId: '186645707534',
    projectId: 'elmasa-502219',
    storageBucket: 'elmasa-502219.firebasestorage.app',
    iosClientId: '186645707534-eqsldonr1m4mis7fv8u87vh47vbhie29.apps.googleusercontent.com',
    iosBundleId: 'com.amir.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA30JCgNeQ98Y0jZQhQ4og3qjsXiRDWGiA',
    appId: '1:186645707534:web:3da6fe2240b4ac9e1f755f',
    messagingSenderId: '186645707534',
    projectId: 'elmasa-502219',
    authDomain: 'elmasa-502219.firebaseapp.com',
    storageBucket: 'elmasa-502219.firebasestorage.app',
  );
}
